config/routes.rb
CPDBoostTemplate::Application.routes.draw do
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  # Gav used this for testing
  # get "/posts/:post_id/votes" => 'votes#create'
  
  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:create, :show, :edit, :update] do
    post :bookmark, on: :member
    delete :remove_bookmark, on: :member
  end
  
  resources :categories, only: [:new, :create, :show]
  
  root to: 'posts#index'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  
  has_many :votes, as: :voteable
  
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :require_user
  
  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.creator = current_user
    
    if @comment.save
      flash[:notice] = "You successfully submitted your comment."
      redirect_to post_path(@post)
    else
      render 'posts/show'      
    end
  end
  
  def destroy
    @post = Post.find_by(slug: params[:post_id])
    @comment = Comment.find_by(post_id: @post.id, user_id: current_user.id)
    @comment.destroy
  
    respond_to do |format|
      format.html do
        redirect_to :back
      end
      format.js {}
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
  
end

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class='row'>
  <div class="col-sm-8 well">
    <span>"<%= comment.body %>"</span>
    <span class='main__delete-comment'>
      <% if logged_in? && current_user == comment.creator || logged_in? && current_user.admin? %>
        <%= link_to post_comment_path(@post, comment), method: 'delete', confirm: "Are you sure?" do %>
          <span class="fa fa-times-circle" aria-hidden="true"></span>
        <% end %>
      <% end %>
    </span>
    <p>
  		<span class='quiet'>by </span><%= link_to comment.creator.username, user_path(comment.creator) %>
  		<small>at <%= display_friendly_date(comment.created_at) %></small>
    </p>
  </div>
</div>