config/routes.rb
CPDBoostTemplate::Application.routes.draw do
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  # Gav used this for testing
  # get "/posts/:post_id/votes" => 'votes#create'
  
  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:create, :show, :edit, :update] do
    post :bookmark, on: :member
    delete :remove_bookmark, on: :member
  end
  
  resources :categories, only: [:new, :create, :show]
  
  root to: 'posts#index'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Sluggable
  
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  
  has_many :comments, dependent: :destroy #removes all associated comments automatically
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :bookmarked_posts
  has_many :users, through: :bookmarked_posts
  has_many :votes, as: :voteable
    
  validates :title, presence: true, uniqueness: true, length: {minimum: 5}
  validates :description, presence: true
  
  #used in the sluggable_knoxjeffrey gem to create a slug based on the name column
  sluggable_column :title
  
  #check if a comment has already been made by a user
  def commented_by_user?(the_user)
    the_user.comments.find_by_post_id(self.id).present?
  end
  
  ########## VOTE ########## 
  #check if a user has already voted on a post
  def voted_by_user?(the_user)
    vote_object(the_user).present?
  end
  
  #return the vote id if it exists
  def vote_object(the_user)
    vote_object = the_user.votes.where(["voteable_id = ? and voteable_type = ?", self.id, self.class.name])
    vote_object.present? ? vote_object.first.id : false
  end
  ##########  END VOTE ##########
  
  
  ########## BOOKMARK ##########
  #check if a user has already bookmarked a post
  def bookmarked_by_user?(the_user)
    bookmark_object(the_user).present?
  end
  
  #return the bookmark object
  def bookmark_object(the_user)
    the_user.bookmarked_posts.find_by_post_id(self.id)
  end
  ##########  END BOOKMARK ##########
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post_params, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show] #shut down routes if a user isn't logged in
  before_action :must_be_creator, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all
  end
  
  def new 
    @post = Post.new
  end
  
  def create
    @post = Post.create(post_params)
    @post.creator = current_user
    @post.image_url = generate_image_url_from_post_url(post_params[:url])

    if @post.save
      flash[:notice] = "You successfully created your post!"
      redirect_to posts_path
    else
      render :new
    end
  end
  
  def show
    @comment = Comment.new
  end
  
  def edit; end
  
  def update
    @post.image_url = generate_image_url_from_post_url(post_params[:url])
    
    if @post.update(post_params)
      flash[:notice] = "You successfully updated your post!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end
  
  #all comments associated with post are automatically destroyed by dependent: :destroy in model
  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  
  def set_post_params
    @post = Post.find_by(slug: params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end
  
  def must_be_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end
  
  def generate_image_url_from_post_url(url)
     GenerateImageUrlFromPostUrl.new(url).return_url_string
  end
  
end

app/views/posts/_bookmark_button.html.erb
<span id="bookmark_button_<%= post.slug %>">
  <% if post.bookmarked_by_user?(current_user) %>
    <%= link_to remove_bookmark_user_path(post, post.bookmark_object(current_user)), method: 'delete', remote: true do %>
      <span class="fa fa-bookmark" aria-hidden="true"></span>
      <% end %>
  <% else %>
    <%= link_to bookmark_user_path(post), method: 'post', remote: true do %>
      <span class="fa fa-bookmark-o" aria-hidden="true"></span>
    <% end %>
  <% end %>
</span>

      

app/views/posts/_form.html.erb
<div class="col-sm-8 well">
	<%= form_for @post do |f| %>

		<%= render 'shared/errors', controller_object: @post %>
	 
  		<div class="form-group">
  			<%= f.label :title %>
  			<%= f.text_field :title, class: "form-control" %>
  		</div>

  		<div class="form-group">
  			<%= f.label :url %>
  			<%= f.text_field :url, class: "form-control" %>
  		</div>

  		<div class="from-group">
  			<%= f.label :description %>
  			<%= f.text_area :description, rows: 5, class: "form-control"  %>
      </div>
      <br/>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |box| %>
        <% box.label(class: "checkbox-inline") { box.check_box(class: 'checkbox') + box.text } %>
      <% end %>
      <br/>
      <br/>
	    <%= f.submit @post.new_record? ? "Submit Post" : "Update Post", class: "btn btn-success" %>

	<% end %>
</div>

app/views/posts/_like_button.html.erb
<span id="like_button_<%= post.slug %>">
  <% if post.voted_by_user?(current_user) %>
    <%= link_to post_vote_path(post, post.vote_object(current_user)), method: 'delete', remote: true do %>
      <span class="fa fa-heart" aria-hidden="true"> <%= post.votes.size %></span>
      <% end %>
  <% else %>
    <%= link_to post_votes_path(post), method: 'post', remote: true do %>
      <span class="fa fa-heart-o" aria-hidden="true"> <%= post.votes.size %></span>
    <% end %>
  <% end %>
</span>

app/views/posts/_post.html.erb
<div class="grid-post">
  <% if post.image_url.present? %>
    <%= image_tag(post.image_url, class: "grid-post__images") %>
    <br>
    <br>
  <% end %>
  <div class='grid-post__info-section'>
    <span><%= render post.categories %></span>
    <% if logged_in? %>
      <span class='grid-post__bookmark'><%= render 'posts/bookmark_button', post: post %></span>
    <% end %>
    <h4><%= link_to post.title, post_path(post) %></h4>
    <p><%= post.description %></p>
    <p><%= link_to post.url, url_with_protocol(post.url) %></p>

    <div class='row'>
      <% if logged_in? %>
        <%= link_to post_path(post) do %>
          <% if post.commented_by_user?(current_user) %>
            <span class="fa fa-comment" aria-hidden="true"> <%= post.comments.size %></span>
          <% else %>
            <span class="fa fa-comment-o" aria-hidden="true"> <%= post.comments.size %></span>
          <% end %>
        <% end %>
        <%= render 'posts/like_button', post: post %>
      <% end %>
    <hr>
    <p>
      <span class='quiet'>posted by </span><%= link_to post.creator.username, user_path(post.creator) %>
      <small><%= display_friendly_date(post.created_at) %> ago</small>
    </p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit Post"%>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% if !logged_in? %>
  <div class='jumbotron'>
    <div id='jumbotron-title'>CPD Boost</div>
    <br>
    <div id='jumbotron-body'>
      Join CPD Boost to find (and save) ideas that you can implement with your clients today.
    </div>
  </div>
<% end %>

<div id='container' class="masonry js-masonry"  data-masonry-options='{ "columnWidth": 60 }'>
  <% @posts.each do |post| %>
  	<div class='item'><%= render 'post', post: post %></div>
  <% end %>
</div>
 

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create New Post"%>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class='main__edit-post'>
  <%if logged_in? && current_user == @post.creator || logged_in? && current_user.admin? %>
    <p class='pull-right'>
    	<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-danger btn-small' %>
      <%= link_to 'Delete', post_path(@post), method: 'delete', confirm: "Are you sure?", class: 'btn btn-danger btn-small' %>
    </p>
  <% end %>

  <p>
  	<%= render @post.categories %>
  </p>
</div>

<p class='lead'>
    <span id='main__post-title'><%= @post.title %></span>
    <% if !@post.url.empty? %>
      <p class='badge post-badge'><%= link_to @post.url, url_with_protocol(@post.url) %></p>
    <% end %>
</p>

<div class='row'>
  <div class="col-sm-12 well">
    <p><%= @post.description %></p>
  </div>
</div>

<% if logged_in?%>
  <div class='row'>
  	<div class='col-sm-8 well'>
      <%= form_for [@post, @comment] do |f| %>
        <%= render 'shared/errors', controller_object: @comment %>
 
      	<div class="form-group">
      		<%= f.label :body, "Leave A Comment" %>
      		<%= f.text_area :body, rows: 5, class: "form-control" %>
      	</div>
        </br>
        <%= f.submit "Create Comment", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
<% end%>

<% if !@post.reload.comments.empty? %>
  <h5>Comments:</h5>
  <br/>
<% end %>

<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>